project/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from app.views import changePassword, changePasswordPanel, home, create, store, painel, dologin, dashboard, logouts, cadastro, editarCadastro, DadosCreate, AdrCreate, DadosUpdate, AdrUpdate

urlpatterns = [
    path('dados/', DadosCreate.as_view(), name='dados-campo'),
    path('endereco/', AdrCreate.as_view(), name='endereco-campo'),
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('create/', create),
    path('cadastro/', cadastro),
    path('editar-cadastro/', editarCadastro),
    path('store/', store),
    path('painel/', painel),
    path('dologin/', dologin),
    path('dashboard/', dashboard, name='dashboard'),
    path('logouts/', logouts),
    path('password/', changePassword),
    path('password-panel/', changePasswordPanel),

    path('editar-dados/<int:pk>/', DadosUpdate.as_view(), name='editar-dados'),
    path('editar-endereco/<int:pk>/', AdrUpdate.as_view(), name='editar-endereco'),
]

app/models.py
from django.db import models

# Create your models here.
class Dados(models.Model):
    cpf = models.CharField(max_length=14)
    pis = models.CharField(max_length=14)

class Adr(models.Model):
    pais = models.CharField(max_length=30)
    municipio = models.CharField(max_length=30)
    uf = models.CharField(max_length=2)
    rua = models.CharField(max_length=50)
    cep = models.CharField(max_length=9)
    num = models.CharField(max_length=10)
    compl = models.CharField(max_length=20)

app/views.py
from dataclasses import field
import email
from re import template
from statistics import mode
from unicodedata import name
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.views.generic.edit import CreateView, UpdateView
from .models import Dados, Adr
from django.urls import reverse_lazy


#Formulário do painel de cadastro
def cadastro(request):
    return render(request,'dashboard/cadastro.html')

#Formulário do painel de editar cadastro
def editarCadastro(request):
    return render(request,'dashboard/editar-cadastro.html')

#Formulário do painel de dados
def dados(request):
    return render(request,'dados.html')

#Formulário do painel de endereço
def endereco(request):
    return render(request,'endereco.html')

#cadastro registros
class DadosCreate(CreateView):
    model = Dados
    fields = ['cpf', 'pis']
    template_name = 'dados.html'
    succes_url = reverse_lazy('dashboard')

#cadastro endereço
class AdrCreate(CreateView):
    model = Adr
    fields = ['pais', 'municipio', 'uf', 'rua', 'cep', 'num', 'compl']
    template_name = 'endereco.html'
    succes_url = reverse_lazy('dashboard')

#update registros
class DadosUpdate(UpdateView):
    model = Dados
    fields = ['cpf', 'pis']
    template_name = 'editar-dados.html'
    succes_url = reverse_lazy('dashboard')

#update endereço
class AdrUpdate(UpdateView):
    model = Adr
    fields = ['pais', 'municipio', 'uf', 'rua', 'cep', 'num', 'compl']
    template_name = 'editar-endereco.html'
    succes_url = reverse_lazy('dashboard')

#Home
def home(request):
    return render(request, 'home.html')

#Formulário de cadastro de usuários
def create(request):
    return render(request, 'create.html')

#Inserção dos dados dos usuários no banco
def store(request):
    data={}
    if not request.POST['name']:
        data['msg'] = 'Preencha TODOS os campos!'
        data['class'] = 'alert-danger'
        return render(request, 'create.html', data)
    if not request.POST['email']:
        data['msg'] = 'Preencha TODOS os campos!'
        data['class'] = 'alert-danger'
        return render(request, 'create.html', data)
    if not request.POST['password']:
        data['msg'] = 'Preencha TODOS os campos!'
        data['class'] = 'alert-danger'
        return render(request, 'create.html', data)
    if not request.POST['password-conf']:
        data['msg'] = 'Preencha TODOS os campos!'
        data['class'] = 'alert-danger'
        return render(request, 'create.html', data)
    if(request.POST['password'] != request.POST['password-conf']):
        data['msg'] = 'As senhas não coincidem!'
        data['class'] = 'alert-danger'
        return render(request, 'create.html', data)
    else:
        user = User.objects.create_user(request.POST['name'], request.POST['email'], request.POST['password'], )
        user.first_name = request.POST['name']
        user.save()
        data['msg2'] = 'Usuário cadastrado com sucesso!'
        data['class'] = 'alert-succes'

    return render(request, 'create.html', data)



#Formulário do painel de login
def painel(request):
    return render(request,'painel.html')

#Processa o login
def dologin(request):
    data = {}
    user = authenticate(username=request.POST['user'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        return redirect('/dashboard/')
    else:
        data['msg'] = 'Usuário ou Senha inválidos!'
        data['class'] = 'alert-danger'
        return render(request,'painel.html',data)

#Processa o logout
def logouts(request):
    logout(request)
    return redirect('/painel/')

#Página inicial do dashboard
def dashboard(request):
    return render(request, 'dashboard/home.html')

#Formulário de troca de senha
def changePasswordPanel(request):
    return render(request, 'dashboard/change-password-panel.html')

#Processa troca de senha
def changePassword(request):
    data={}
    if(request.POST['new_password1'] != request.POST['new_password2']):
        data['msg'] = 'As senhas não coincidem!'
        data['class'] = 'alert-danger'
        return render(request, 'dashboard/change-password-panel.html', data)
    else:
        user = User.objects.get(email=request.user.email)
        user.set_password(request.POST['new_password1'])
        user.save()
        logout(request)
        return redirect('/painel/')

app/templates/create.html
{% extends 'main.html' %}

{% block content %}
<form name="form-users" id="formUsers" method="post" action="/store/">
    <div class="container">
        {% csrf_token %}
        <div class="screen">
            <div class="screen__content">
                <form class="login">
                    <h1 class="login__title">Cadastrar-se</h1>

                    <div class="login__field">
                        <i class="login__icon fas fa-user"></i>
                        <input class="login__input" type="text" name="name" id="name" placeholder="Primeiro Nome:">
                    </div>

                    <div class="login__field">
                        <i class="login__icon fas fa-user"></i>
                        <input class="login__input" type="email" name="email" id="email"
                            placeholder="Digite seu E-mail:">
                    </div>

                    <div class="login__field">
                        <i class="login__icon fas fa-user"></i>
                        <input class="login__input" type="password" name="password" id="password"
                            placeholder="Crie uma senha:">
                    </div>

                    <div class="login__field">
                        <i class="login__icon fas fa-user"></i>
                        <input class="login__input" type="password" name="password-conf" id="password-conf"
                            placeholder="Confirme a senha:">
                    </div>
                    {% if msg %}
                    <div class="alert {{class}}">
                        {{msg}}
                    </div>
                    {% endif %}
                    {% if msg2 %}
                    <div class="alert2 {{class}}">
                        {{msg2}}
                    </div>
                    {% endif %}
                    <button class="button login__submit">
                        <span class="button__text">Cadastrar</span>
                    </button>
                </form>
                <a href="/">Home</a><br>
            </div>
        </div>
    </div>
</form>
<script src="app/static/js/javascript.js"></script>
{% endblock %}

app/templates/dados.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
{% if request.user.is_authenticated %}
<h3>Cadastro</h3>

<p>
    Preencha todos os campos.
</p>

<hr>

<form action="" method="post">
    {% csrf_token %}
      <p>
        <label for="id_cpf">CPF:</label>
        <input type="text" name="cpf" maxlength="14" required id="id_cpf">
      </p>

      <p>
        <label for="id_pis">PIS:</label>
        <input type="text" name="pis" maxlength="14" required id="id_pis">
      </p>

    <button type="submit">
        Cadastrar
    </button>
</form>

<a href="/dashboard/">Home</a><br>
{% else %}
        Acesso negado! <a href="/painel/">Realize o login</a> para poder entrar.
    {% endif %}
{% endblock %}

app/templates/dashboard/cadastro.html
{% extends 'main.html' %}

{% block content %}
    {% if request.user.is_authenticated %}
        <h1>Área Restrita</h1>
        Crie tabelas com de dados e endereço:<br>
        Informe <a href="/dados/">alguns dados.</a><br>
        Informe <a href="/endereco/">seu endereco.</a><br>
        <a href="/dashboard/">Home</a><br>
        <a href="/logouts/">Sair</a>
    {% else %}
        Acesso negado! <a href="/painel/">Realize o login</a> para poder entrar.
    {% endif %}
{% endblock %}

app/templates/dashboard/change-password-panel.html
{% extends 'main.html' %}

{% block content %}
    {% if request.user.is_authenticated %}
        <form name="formChange-password" id="formChange-password" method="post" action="/password/">
            <div class="container">
                {% csrf_token %}
                <div class="screen">
                    <div class="screen__content">
                        <form class="login">
                            <h1 class="login__title">Troca de Senha</h1>

                            <div class="login__field">
                                <i class="login__icon fas fa-user"></i>
                                <input class="login__input" type="password" name="new_password1" id="new_password1" placeholder="Senha Nova:">
                            </div>

                            <div class="login__field">
                                <i class="login__icon fas fa-user"></i>
                                <input class="login__input" type="password" name="new_password2" id="new_password2" placeholder="Confirme a Senha Nova:">
                            </div>

                            {% if msg %}
                                <div class="alert {{class}}">
                                    {{msg}}
                                </div>
                            {% endif %}
                            <button class="button login__submit">
                                <span class="button__text">Alterar</span>
                            </button>				
                        </form>
                        <div class="by">
                            <h3>by.julio</h3>
                        </div>
                    </div>		
                </div>
            </div>
        </form>
        <a href="/dashboard/">Home</a><br>
    {% else %}
        Acesso negado! <a href="/painel/">Realize o login</a> para poder entrar.
    {% endif %}
    {% endblock %}

app/templates/dashboard/editar-cadastro.html
{% extends 'main.html' %}

{% block content %}
    {% if request.user.is_authenticated %}
        <h1>Área Restrita</h1>
        Instruções para editar cadastro:<br>
            - Se quer editar uma tabela de endereço o link é: /editar-endereço/ <br>
            - Se quer editar uma tabela de dados o link é: /editar-dados/ <br>
            - Coloque o ID da tabela que você quer editar no final do link entre barras '//' <br>
                Ex.: <br>
                 - Quero editar a tabela de ID 7 de dados <br>
                 - Link: /editar-dados/7/ <br>

                 Ex.2: <br>
                 - Quero editar a tabela de ID 4 de endereço <br>
                    - Link: /editar-endereco/4/ <br>
        
            obs.: a tabela tem que existir.
            <a href="/dashboard/">Home</a><br>
    {% else %}
        Acesso negado! <a href="/painel/">Realize o login</a> para poder entrar.
    {% endif %}
{% endblock %}

app/templates/dashboard/home.html
{% extends 'main.html' %}

{% block content %}
    {% if request.user.is_authenticated %}
        <h1>Área Restrita</h1>
        Bem Vindo!<br>
        <a href="/password-panel/">Alterar Senha</a><br>
        <a href="/logouts/">Sair</a>
    {% else %}
        Acesso negado! <a href="/painel/">Realize o login</a> para poder entrar.
    {% endif %}
{% endblock %}

app/templates/editar-dados.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
{% if request.user.is_authenticated %}
<h3>Cadastro</h3>

<p>
    Preencha todos os campos.
</p>

<hr>

<form action="" method="post">
    {% csrf_token %}
    <p>
        <label for="id_cpf">Cpf:</label>
        <input type="text" name="cpf" maxlength="14" required id="id_cpf">
        
        
      </p>
      <p>
        <label for="id_pis">Pis:</label>
        <input type="text" name="pis" maxlength="14" required id="id_pis">
        
        
          
        
      </p>

    <button type="submit">
        Salvar Alterações
    </button>
</form>

<a href="/dashboard/">Home</a><br>
{% else %}
        Acesso negado! <a href="/painel/">Realize o login</a> para poder entrar.
    {% endif %}
{% endblock %}

app/templates/editar-endereco.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
{% if request.user.is_authenticated %}
<h3>Cadastro</h3>

<p>
    Preencha todos os campos.
</p>

<hr>

<form action="" method="post">
    {% csrf_token %}

      <p>
        <label for="id_cpf">Pais:</label>
        <input type="text" name="pais" maxlength="30" required id="id_pais">
        
      </p>
      <p>
        <label for="id_pis">Municipio:</label>
        <input type="text" name="municipio" maxlength="30" required id="id_municipio">
        
      </p>
      <p>
        <label for="id_pis">UF:</label>
        <input type="text" name="uf" maxlength="2" required id="id_uf">
        
      </p>
      <p>
        <label for="id_pis">Rua:</label>
        <input type="text" name="rua" maxlength="50" required id="id_rua">
        
      </p>
      <p>
        <label for="id_pis">CEP:</label>
        <input type="text" name="cep" maxlength="9" required id="id_cep">
        
      </p>
      <p>
        <label for="id_pis">Número:</label>
        <input type="text" name="num" maxlength="10" required id="id_num">
        
      </p>
      <p>
        <label for="id_pis">Complemento:</label>
        <input type="text" name="compl" maxlength="20" required id="id_compl">
        
      </p>

    <button type="submit">
        Salvar Alterações
    </button>
</form>

<a href="/dashboard/">Home</a><br>
{% else %}
        Acesso negado! <a href="/painel/">Realize o login</a> para poder entrar.
    {% endif %}
{% endblock %}

app/templates/endereco.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
{% if request.user.is_authenticated %}
<h3>Cadastro</h3>

<p>
    Preencha todos os campos.
</p>

<hr>

<form action="" method="post">
    {% csrf_token %}

      <p>
        <label for="id_cpf">Pais:</label>
        <input type="text" name="pais" maxlength="30" required id="id_pais">
        
      </p>
      <p>
        <label for="id_pis">Municipio:</label>
        <input type="text" name="municipio" maxlength="30" required id="id_municipio">
        
      </p>
      <p>
        <label for="id_pis">UF:</label>
        <input type="text" name="uf" maxlength="2" required id="id_uf">
        
      </p>
      <p>
        <label for="id_pis">Rua:</label>
        <input type="text" name="rua" maxlength="50" required id="id_rua">
        
      </p>
      <p>
        <label for="id_pis">CEP:</label>
        <input type="text" name="cep" maxlength="9" required id="id_cep">
        
      </p>
      <p>
        <label for="id_pis">Número:</label>
        <input type="text" name="num" maxlength="10" required id="id_num">
        
      </p>
      <p>
        <label for="id_pis">Complemento:</label>
        <input type="text" name="compl" maxlength="20" required id="id_compl">
        
      </p>

    <button type="submit">
        Cadastrar
    </button>
</form>

<a href="/dashboard/">Home</a><br>
{% else %}
        Acesso negado! <a href="/painel/">Realize o login</a> para poder entrar.
    {% endif %}
{% endblock %}

app/templates/home.html
{% extends 'main.html' %}

{% block content %}
    Olá, visitante! <br>
    <a href="/create/">Cadastro de Usuários</a><br>
    <a href="/painel/">Painel de Login</a>
    {% endblock %}

app/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro e Login</title>
</head>
<body>
    {% block content %}
    {% endblock %}
    <!-- tag de comando, o arquivo 'main.html' vai ser puxado no arquivo 'home.html' como extensão.-->
    
    <script src="{% static 'js/javascript.js' %}"></script>
</body>
</html>

app/templates/painel.html
{% extends 'main.html' %}

{% block content %}
    <form name="formPainel" id="formPainel" method="post" action="/dologin/">
        <div class="container">
            {% csrf_token %}
            <div class="screen">
                <div class="screen__content">
                    <form class="login">
                        <h1 class="login__title">Login</h1>

                        <div class="login__field">
                            <i class="login__icon fas fa-lock"></i>
                            <input class="login__input" type="text" name="user" id="user" placeholder="Usuário:">
                        </div>

                        <div class="login__field">
                            <i class="login__icon fas fa-user"></i>
                            <input class="login__input" type="password" name="password" id="password" placeholder="Senha:">
                        </div>
                        
                        {% if msg %}
                            <div class="alert {{class}}">
                                {{msg}}
                            </div>
                        {% endif %}
                        {% if msg2 %}
                            <div class="alert {{class}}">
                                {{msg2}}
                            </div>
                        {% endif %}
                        <button class="button login__submit">
                            <span class="button__text">Entrar</span>
                        </button>				
                    </form>
                    <a href="/">Home</a><br>
                </div>		
            </div>
        </div>
    </form>
    {% endblock %}